name: Haskell CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v13

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: fts
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix-shell --run "nix-build-uncached default.nix" nix/ci.nix
